---
title: "R语言实现随机森林(3)Test the model"
author: "jmzeng@163.com"
date: "6/12/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


> * [我的博客](http://www.bio-info-trainee.com/)
 * [我们的论坛](http://www.biotrainee.com/forum.php)
 * [捐赠我](http://www.bio-info-trainee.com/donate)


## 首先加载包，并且加载上一步骤的数据
```{r,warning=FALSE,message=FALSE}
library(randomForest)
library(ROCR)
require(Hmisc)
load('rf_output.Rdata')
load('ML_RF_input.Rdata')

```

## 把test数据集准备成随机森林模型预测需要的input格式

```{r}
predictor_data=t(testing_data)
predictor_data[1:4,1:4]
dim(predictor_data)
RF_predictor_names=rownames(rf_output$importance)
predictor_data=predictor_data[,RF_predictor_names]
predictor_data[1:4,1:4]
dim(predictor_data)
```


## 应用随机森林模型来进行预测
```{r}
RF_predictions_responses=predict(rf_output, predictor_data, type="response")
RF_predictions_votes=predict(rf_output, predictor_data, type="vote")
head(RF_predictions_responses)
head(RF_predictions_votes)
```


## 预测结果的一些评价指标

### 首先要把预测结果与test数据的真实临床表型数据结合起来

```{r}

head(testing_clinical)
clindata=testing_clinical[,c('event.rfs','time.rfs')]
clindata_plusRF=cbind(clindata,RF_predictions_responses,RF_predictions_votes)
dim(clindata_plusRF)
clindata_plusRF=clindata_plusRF[! is.na(clindata_plusRF$event.rfs)  ,]
dim(clindata_plusRF)
head(clindata_plusRF)

save(clindata_plusRF,file='predictor_output.Rdata')
```

### 简单模型诊断，可以计算 sensitivity, specificity, accuracy 等等

```{r}
confusion=table(clindata_plusRF[,c("event.rfs","RF_predictions_responses")])
rownames(confusion)=c("NoRelapse","Relapse")
confusion

sensitivity=(confusion[2,2]/(confusion[2,2]+confusion[2,1]))*100
sensitivity
specificity=(confusion[1,1]/(confusion[1,1]+confusion[1,2]))*100
specificity
overall_error=((confusion[1,2]+confusion[2,1])/sum(confusion))*100
overall_error
overall_accuracy=((confusion[1,1]+confusion[2,2])/sum(confusion))*100
overall_accuracy
class1_error=confusion[1,2]/(confusion[1,1]+confusion[1,2])
class1_error
class2_error=confusion[2,1]/(confusion[2,2]+confusion[2,1])
class2_error
```

### ROC curve and calculate the area under it (AUC)

```{r}
# Create variables for the known target class and predicted class probabilities.
target=clindata_plusRF[,"event.rfs"]
target[target==1]="Relapse"
target[target==0]="NoRelapse"
relapse_scores=clindata_plusRF[,"Relapse"]
# First calculate the AUC value.
pred=prediction(relapse_scores,target)
perf_AUC=performance(pred,"auc")
AUC=perf_AUC@y.values[[1]]
AUC_out=paste("AUC=",AUC,sep="")
# Then, plot the actual ROC curve.
perf_ROC=performance(pred,"tpr","fpr")
plot(perf_ROC, main="ROC plot")
text(0.5,0.5,paste("AUC = ",format(AUC, digits=5, scientific=FALSE)))
```







